# Generated by Django 5.0.6 on 2026-07-12 05:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_tag', models.CharField(blank=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('ALLOCATED', 'Allocated'), ('UNDER_MAINTENANCE', 'Under Maintenance'), ('RETIRED', 'Retired'), ('LOST', 'Lost')], default='AVAILABLE', max_length=20)),
                ('qr_code_value', models.CharField(blank=True, max_length=100, unique=True)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['asset_tag'],
            },
        ),
    ]
