# Generated by Django 5.0.6 on 2026-07-12 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='title',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
